### ISSUE TITLE
Which version of boost are you using?

### ISSUE THREAD

**Issue by daerduoCarey** [mtatarchenko/ogn#1]
Hi, 

Thank you for releasing the code. We are very interested in your paper and are now trying to use your code to reproduce the experiments in your paper. But we cannot successfully compile your released version of caffe. Here is the error.

`.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::archive::detail::basic_oserializer'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::is_equal(boost::serialization::extended_type_info const&) const'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::archive::detail::basic_iarchive'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::extended_type_info::key_register() const'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::type_unregister()'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::is_less_than(boost::serialization::extended_type_info const&) const'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::archive::detail::basic_iserializer'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::basic_text_iprimitive<std::istream>::~basic_text_iprimitive()'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::archive::archive_exception'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::serialization::typeid_system::extended_type_info_typeid_0'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_iserializer::~basic_iserializer()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load_override(boost::archive::class_name_type&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_oserializer::~basic_oserializer()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::extended_type_info_typeid_0(char const*)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_oserializer::basic_oserializer(boost::serialization::extended_type_info const&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_oarchive::save_object(void const*, boost::archive::detail::basic_oserializer const&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::extended_type_info::key_unregister() const'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_oarchive::~basic_oarchive()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::archive_exception::~archive_exception()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::basic_text_oarchive<boost::archive::text_oarchive>::newtoken()'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::~extended_type_info_typeid_0()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_iarchive::get_library_version() const'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::text_oarchive_impl(std::ostream&, unsigned int)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_iarchive::~basic_iarchive()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::basic_text_oprimitive<std::ostream>::~basic_text_oprimitive()'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_oarchive::end_preamble()'
.build_release/lib/libcaffe.so: undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::type_register(std::type_info const&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_iarchive::reset_object_address(void const*, void const*)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::text_iarchive_impl(std::istream&, unsigned int)'
.build_release/lib/libcaffe.so: undefined reference to `boost::archive::detail::basic_iserializer::basic_iserializer(boost::serialization::extended_type_info const&)'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::archive::detail::basic_oarchive'`

Seems like we are using the wrong version of boost? Any idea? Thank you for helping me!

Bests,
Kaichun Mo

**Comment by tatarchm** [comment]
Hi,

I tried it with Boost 1.57.0 and 1.61.0, both work. It seems that the binaries of the Boost.Serialization module are not found in your setup. Have you compiled Boost yourself? Does caffe find the correct path to the Boost binary libs?

Best,
Maxim

**Comment by daerduoCarey** [comment]
Hi, Maxim,

Thank you for the prompt reply. I found this is a simple link error. I fixed the problem by adding -lboost_serialization flags. Also failed to compile the original caffe. Now adding the flags fixed them. Thank you for the code! They are super helpful! Great job!

Bests,
Kaichun

**Comment by alitou** [comment]
How did you add the flags?

**Comment by tatarchm** [comment]
You can add the flags to 'cmake/Dependencies.cmake'.
