### ISSUE TITLE
Reading both .binvox and .oc for auto encoder tests

### ISSUE THREAD

**Issue by anastasiadk** [mtatarchenko/ogn#10]
Hi Maxim,

thanks for sharing the code.
I'd like to repeat your auto encoder tests. Assuming you used dense voxel grids encoded as .binvox - do you have a reader to load matching pairs of .binvox and .oc files? Could you share it, or explain how you circumvented this?

Thanks in advance,
Anastasia

**Comment by tatarchm** [comment]
Hi Anastasia,

Thank you for your interest in our work.

There is a C++ function for loading .binvox files (VoxelGrid::read_binvox). In my experiments, I used a different version of the framework containing a wrapper layer which was calling this function. I can port this layer to the current framework, but I will only be able to do it in the end of November or so. Alternatively, you can write such a layer yourself. It only requires reading a file and passing its content to the output blob.

The order of .binvox and .ot files was synchronized by simply providing the corresponding 'model_names' files for each of the two types.

Best,
Maxim

**Comment by anastasiadk** [comment]
Hi Maxim,

thanks for the reply. Indeed it is a good solution.
I did something similar - I used a python layer to load binvox (without using VoxelGrid::read_binvox), and passed the indices of binvox files to ogn_data_layer. The only cumbersome part was to maintain a compatible list of indices for .binvox and .ot files. Having a single layer to load pairs of .binvox and .ot files could be a better solution. If I get to it, I'll update you.

Best,
Anastasia

**Comment by bensnell** [comment]
Hi @tatarchm,

To follow up, were you able to upload the aforementioned wrapper layer for loading binvox files?

Also, if I may ask for clarification of a previous point: When you mention _"The order of .binvox and .ot files was synchronized by simply providing the corresponding 'model_names' files for each of the two types."_, this means loading two files with the same ordering, like the example files below...

**model_names_binvox.txt**
```
path/to/model_001.binvox
path/to/model_002.binvox
path/to/model_003.binvox
```

**model_names_ot.txt**
```
path/to/model_001.ot
path/to/model_002.ot
path/to/model_003.ot
```

... where **model_names_binvox.txt** is loaded to your custom binvox layer, and **model_names_ot.txt** is loaded to OGNDataLayer, correct?

Thank you so much,
Ben

**Comment by tatarchm** [comment]
> To follow up, were you able to upload the aforementioned wrapper layer for loading binvox files?

No, I did not add such a wrapper.

> Also, if I may ask for clarification of a previous point: When you mention "The order of .binvox and .ot files was synchronized by simply providing the corresponding 'model_names' files for each of the two types.", this means loading two files with the same ordering, like the example files below...

> model_names_binvox.txt

> path/to/model_001.binvox
> path/to/model_002.binvox
> path/to/model_003.binvox
> model_names_ot.txt

> path/to/model_001.ot
> path/to/model_002.ot
> path/to/model_003.ot
> ... where model_names_binvox.txt is loaded to your custom binvox layer, and model_names_ot.txt is loaded to OGNDataLayer, correct?

Exactly.
