### ISSUE TITLE
Inputting octrees directly

### ISSUE THREAD

**Issue by gregkocher** [mtatarchenko/ogn#11]
It seems from some of the included example nets [e.g. within single_view_3d] that you output octree predictions but you start with depth renderings/voxels, and use the octree .ot files as ground truth at various levels but not directly as input.

With your available code and layers, is it possible to load octree .ot files [using the ogn_data_layer] and have the network work entirely in the octrees space [doing octree convs etc.] and entirely bypass the voxel input representation? In other words, to work purely in the octree representation, learning a set of octree predictions Y from a set of input octrees X?

**Comment by tatarchm** [comment]
Out method does not provide a way to input octrees, it's only an decoder. You may want to check out other works which can process input octrees: https://arxiv.org/abs/1611.05009 and http://wang-ps.github.io/O-CNN. Both can be used in combination with our decoder.
