### ISSUE TITLE
"single_view_3d/Shapenet_cars/snapshot/snapshot_iter_136000.caffemodel" corresponds to pred or known network ?

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [mtatarchenko/ogn#14]
single_view_3d/Shapenet_cars/snapshot/snapshot_iter_136000.caffemodel corresponds to pred or known network ?  I couldn't figure it out, I'm not familiar with caffe. Great work !!

**Comment by tatarchm** [comment]
This snapshots should be compatible with all network specifications. It was obtained as the output of the 'pred' network though. If you don't need to re-train anything and only want to use this snapshot, you can run the 'test.sh' script.

**Comment by ThibaultGROUEIX** [comment]
Noted ! Thank you for being so responsive ! I've run it successfully.
