### ISSUE TITLE
Compilation error: "undefined reference to 'caffe::OGNConvLayer<float>...'

### ISSUE THREAD

**Issue by irequireversioncontrol** [mtatarchenko/ogn#15]
Hi Maxim,
I have tried to compile from several different machines and using both make and cmake (always on Ubuntu 17). I always get the same error (see below).

![image](https://user-images.githubusercontent.com/24638872/35334964-68cba23e-0114-11e8-93c9-a74d45326b28.png)

I have gone through all the closed issues but have not found anything similar. Please let me know if you have any idea what this is about. 
All the best,
irequireversioncontrol

**Comment by tatarchm** [comment]
Hi,

It seems the GPU versions of functions were not compiled, and thus the linker cannot find them. Can you check whether you have set correct paths to the CUDA toolkit? Also, the only build method currently supported is CMake. If you want to use Makefiles, you need to configure things yourself.

**Comment by irequireversioncontrol** [comment]
Thank you, Maxim. It was indeed a CUDA path issue. It has now compiled well.
