### ISSUE TITLE
Memory issue when training OGN with different data

### ISSUE THREAD

**Issue by pookiefoof** [mtatarchenko/ogn#17]
Thanks for sharing the code and data of the OGN project, and they are very helpful. But I ran into some problems while trying to train OGN from scratch using our own data:

For example, for the "shape from ID" network, I was able to run the provided configuration successfully. However, when trying to train the network with the *prop-known* option using our own data, I kept running into the "out of memory" error (an NVIDIA GTX 1080Ti with 11GB memory was used) while doing the backward propagation; meanwhile, surprisingly, the *prop-pred* routine was able to work without any error. Even when I tried to train the network with the provided ShapeNetVox32 data, the same error persisted. 

Hope you can provide some clues about this problem. Thank you!

p.s. A snapshot of the error message:
![image](https://user-images.githubusercontent.com/3117031/36781566-2afc4f86-1cb1-11e8-9fdd-b1cd2fdcedc1.png)

**Comment by bensnell** [comment]
What was the solution to this problem? I'm facing a similar issue. 

The only way I can fix it is by restarting my computer. However, after about 4 hours of training with PROP_KNOWN, the problem comes back.

Thank you,
Ben

**Comment by tatarchm** [comment]
From what @pookiefoof wrote me, I can tell that something was wrong with the min_level parameter he used when converting data using ogn_converter.
