### ISSUE TITLE
Compilation was successful, but there was an error when using train_known.sh

### ISSUE THREAD

**Issue by Jee-King** [mtatarchenko/ogn#19]
`I0320 05:16:26.115514  4794 solver.cpp:87] Creating training net from net file: train_known.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 9:18: Message type "caffe.LayerParameter" has no field named "ogn_data_param".
F0320 05:16:26.115581  4794 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_known.prototxt
`
I think this error is related to compilation. Waitting for your help.

**Comment by tatarchm** [comment]
Hi,

Can you please provide more details? Which experiment are you running? Did you compile using CMake?

Thanks,
Maxim

**Comment by Ji-qing** [comment]
Hi，thanks for your reply
I compiled using cmake and make according to ogn/Docker/gpu/dockerfile.
And running  'train_known.sh' or 'train_pred.sh' both lead to this error.
More details,
`root@iccd-937:/taylor/shape_from_id/shapenet_cars_256# ./train_known.sh 
I0321 03:26:22.302407  6765 upgrade_proto.cpp:1082] Attempting to upgrade input file specified using deprecated 'solver_type' field (enum)': solver_known.prototxt
I0321 03:26:22.302973  6765 upgrade_proto.cpp:1089] Successfully upgraded file specified using deprecated 'solver_type' field (enum) to 'type' field (string).
W0321 03:26:22.302979  6765 upgrade_proto.cpp:1091] Note that future Caffe releases will only support 'type' field (string) for a solver's type.
I0321 03:26:22.303552  6765 caffe.cpp:218] Using GPUs 0
I0321 03:26:22.312072  6765 caffe.cpp:223] GPU 0: GeForce GTX 1080 Ti
I0321 03:26:22.759819  6765 solver.cpp:44] Initializing solver from parameters: 
base_lr: 0.001
display: 1
max_iter: 300000
lr_policy: "multistep"
gamma: 0.1
momentum: 0.9
snapshot: 2000
snapshot_prefix: "snapshots/snapshot"
solver_mode: GPU
device_id: 0
debug_info: false
net: "train_known.prototxt"
train_state {
  level: 0
  stage: ""
}
stepvalue: 30000
stepvalue: 70000
momentum2: 0.999
type: "Adam"
I0321 03:26:22.760069  6765 solver.cpp:87] Creating training net from net file: train_known.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 9:18: Message type "caffe.LayerParameter" has no field named "ogn_data_param".
F0321 03:26:22.760229  6765 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_known.prototxt
*** Check failure stack trace: ***
    @     0x7f4b4c0405cd  google::LogMessage::Fail()
    @     0x7f4b4c042433  google::LogMessage::SendToLog()
    @     0x7f4b4c04015b  google::LogMessage::Flush()
    @     0x7f4b4c042e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4b4c5fac81  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f4b4c5c4d0c  caffe::Solver<>::InitTrainNet()
    @     0x7f4b4c5c60b5  caffe::Solver<>::Init()
    @     0x7f4b4c5c63cf  caffe::Solver<>::Solver()
    @     0x7f4b4c59b521  caffe::Creator_AdamSolver<>()
    @           0x416dac  caffe::SolverRegistry<>::CreateSolver()
    @           0x40e67d  train()
    @           0x40b8a3  main
    @     0x7f4b4ad2c830  __libc_start_main
    @           0x40c249  _start
    @              (nil)  (unknown)
`

**Comment by Jee-King** [comment]
Hi，thanks for your reply
I compiled using cmake and make according to ogn/Docker/gpu/dockerfile.
And running 'train_known.sh' or 'train_pred.sh' both lead to this error.
More details,
![2018-03-21 03-37-14](https://user-images.githubusercontent.com/24266511/37652375-401f7d28-2c76-11e8-8f80-06b53ede9f6b.png)

**Comment by tatarchm** [comment]
I've never actually tested the system with docker builds. Would it be possible for you to try using a regular CMake build procedure, i.e.

```bash
mkdir build
cd build
cmake ..
make all
```

**Comment by Jee-King** [comment]
I solved this problem with your help. Thanks very much !!
