### ISSUE TITLE
OGN_Data_Layer error: boost::serialization

### ISSUE THREAD

**Issue by daerduoCarey** [mtatarchenko/ogn#2]
Hi, Maxim,

Sorry to bother you again. I successfully compiled your code and when running test.sh, I get this error.

`terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
*** Aborted at 1496008197 (unix time) try "date -d @1496008197" if you are using GNU date ***
PC: @     0x7f75d2e94cc9 (unknown)
*** SIGABRT (@0x439600001853) received by PID 6227 (TID 0x7f75d5531780) from PID 6227; stack trace: ***
    @     0x7f75d2e94d40 (unknown)
    @     0x7f75d2e94cc9 (unknown)
    @     0x7f75d2e980d8 (unknown)
    @     0x7f75d34a5bbd (unknown)
    @     0x7f75d34a3b96 (unknown)
    @     0x7f75d34a3be1 (unknown)
    @     0x7f75d34a3df8 (unknown)
    @     0x7f75d3786754 (unknown)
    @     0x7f75d3791631 (unknown)
    @     0x7f75d37916b8 (unknown)
    @     0x7f75d479bc40 GeneralOctree<>::from_file()
    @     0x7f75d479ca07 caffe::OGNDataLayer<>::select_next_batch_models()
    @     0x7f75d479cdff caffe::OGNDataLayer<>::Reshape()
    @     0x7f75d471a41a caffe::Net<>::ForwardFromTo()
    @     0x7f75d471a7c7 caffe::Net<>::Forward()
    @           0x407cb6 test()
    @           0x405af3 main
    @     0x7f75d2e7fec5 (unknown)
    @           0x4063d5 (unknown)
    @                0x0 (unknown)
./test.sh: line 1:  6227 Aborted`

I guess this is because you are using boost::serialization package to organize your octree data, right? Why the version is not supported? can you provide some advice?  BTW, I'm using boost v1.57.0.

Thank you very much!

Bests,
Kaichun

**Comment by daerduoCarey** [comment]
I found that I can use your provided `ogn_convert` to generate my own `.ot` file and your pre-trained model can run on this. Maybe our boost version is not the same so that I cannot directly read your pre-generated `.ot` file in `data.zip`. 

Can you provide a script on how do you get the data in `data.zip`? Thank you!

Bests,
Kaichun

**Comment by tatarchm** [comment]
Hi Kaichun,

I will upload the data in .binvox format, and provide the conversion scripts. Meanwhile, you could try switching to a newer boost version. I'm not sure why the problem occurs, but I just tried compiling the system from scratch on a different machine with boost 1.61.0, and everything works.

Best,
Maxim

**Comment by daerduoCarey** [comment]
Thank you. I tried boost version 1.61 and now it works!
