### ISSUE TITLE
About the provided Example models

### ISSUE THREAD

**Issue by cherryMo** [mtatarchenko/ogn#20]
I am learning the OGN, I wonder to know that  is the provided example models are trained just for the car category? If so,could you provide the other category(shapenet-all)?

**Comment by tatarchm** [comment]
The model for Shapenet-all was only trained in low resolution (32^3) - a case where OGN does not have advantages compared to dense voxel networks. The intention of this experiment was to show that the octree-based network is not inferior to dense networks. Therefore, we do not provide this model and do not recommend using it for comparison.
