### ISSUE TITLE
Testing on own image

### ISSUE THREAD

**Issue by frapaosan** [mtatarchenko/ogn#21]
Hi sorry to bother you again.

Maybe I'm not just seeing it but is there a way to test the trained network on a single input image and output the predicted octree?

Also, I can't seem to find the renderings of shapenet-cars. Is there a link that I missed?

Thanks!

**Comment by frapaosan** [comment]
Or should I just manually get shapet-net cars from shapenet-all?

**Comment by tatarchm** [comment]
Hi,

The renderings are here ftp://cs.stanford.edu/cs/cvgl/ShapeNetRendering.tgz. This archive contains all classes including cars, you can use them.

You can test the network on the same data it was trained on by executing 'test.sh'. It should output predicted octrees to the 'output' folder. If you want to test it on a different dataset or with a different batch size, you have to modify the corresponding parameters in the 'INPUT DATA' section of the 'test_net.prototxt' file.

**Comment by frapaosan** [comment]
This is noted with thanks, tatarchm!
