### ISSUE TITLE
no field named "ogn_data_param"

### ISSUE THREAD

**Issue by whu-lyh** [mtatarchenko/ogn#23]
hello there ,i'm interested about you nn and your ideas.but when i recomplie your code,there comes a error:
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 14:18: Message type "caffe.LayerParameter" has no field named "ogn_data_param".
 and i don't know how to solve this problem。。。can u fix this?thanks...

**Comment by tatarchm** [comment]
Have you compiled the code using CMake?

**Comment by whu-lyh** [comment]
Emmmm。。。i figured it out. Should i recomplie caffe using ogn-master? i'v complie caffe+cuda9.0

**Comment by whu-lyh** [comment]
And there is anather question,what GPU-size does this network works? will 8G enough?

**Comment by tatarchm** [comment]
I'm not sure what you mean by recompiling caffe using ogn-master. You need to compile the caffe version which is provided in the ogn repository - it is different from the standard caffe.

Regarding the GPU size, it depends on the model resolution and the network architecture you use. I think 8G should be enough for at least 128^3 models.

**Comment by whu-lyh** [comment]
ok，i get it, thank you very much..
