### ISSUE TITLE
How to obtain 3D models of resolutions of 128^3

### ISSUE THREAD

**Issue by hzxie** [mtatarchenko/ogn#25]
The given examples only predict 3D models of resolutions of 64^3.
Could you tell me how to obtain 3D models of resolutions of 128^3?

Thank you!

**Comment by dongdu3** [comment]
Hi @hzxie ，

Maybe you have gotten the answer. I think it is given in the readme file. Using 'binvox' to obtain 128 res voxel data, then applying 'tools/ogn_converter', maybe works.

**Comment by hzxie** [comment]
@dongdu3 Thank you.
I forgot to close this issue.
