### ISSUE TITLE
boost::archive::archive_exception

### ISSUE THREAD

**Issue by kealennieh** [mtatarchenko/ogn#4]
Hi, Maxim,

It's helpful of your work. It seems so great to bring in octree. Now, I've compiled successfully the code. However, the error happens when I run the code. 

```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
*** Aborted at 1504245818 (unix time) try "date -d @1504245818" if you are using GNU date ***
PC: @     0x7fa753c95428 gsignal
*** SIGABRT (@0x3eb0000488e) received by PID 18574 (TID 0x7fa7646cbac0) from PID 18574; stack trace: ***
    @     0x7fa763cbf390 (unknown)
    @     0x7fa753c95428 gsignal
    @     0x7fa753c9702a abort
    @     0x7fa7542cf84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fa7542cd6b6 (unknown)
    @     0x7fa7542cd701 std::terminate()
    @     0x7fa7542cd919 __cxa_throw
    @     0x7fa763ee21b7 boost::serialization::throw_exception<>()
    @     0x7fa763eea1fc boost::archive::text_iarchive_impl<>::load()
    @     0x7fa763eea585 boost::archive::basic_text_iarchive<>::init()
    @     0x7fa763eea728 boost::archive::text_iarchive_impl<>::text_iarchive_impl()
    @           0x6ad974 caffe::OGNDataLayer<>::select_next_batch_models()
    @           0x6ae39c caffe::OGNDataLayer<>::Reshape()
    @           0x51fb3a caffe::Net<>::ForwardFromTo()
    @           0x51ff07 caffe::Net<>::Forward()
    @           0x4fba17 test()
    @           0x4eee40 main
    @     0x7fa753c80830 __libc_start_main
    @           0x4fa1c9 _start
    @                0x0 (unknown)
```

I've already seen the closed answer section, where it seems to have a similar one. So I did what it said and tried newer version Boost 1.61.0.  Unfortunately, the error still existed.  Therefore, I check my error and that one carefully. The only difference is that mine is **input stream error** and that one is **unsupported version.** So I guess there may be tiny error in the code. Thanks in advance!

Best wishes,
Kealen

**Comment by kealennieh** [comment]
I've already found where the issue is. Thanks anyway!

**Comment by tatarchm** [comment]
Could you please share what the problem was and how you solved it? Thank you!

**Comment by kealennieh** [comment]
It's not a big problem. As I mentioned above, it turns out to be input stream error. 

When I run ./test.sh, my **test_dataset.txt**, which I made by myself, only contains the path, and doesn't include index. After I read the source code, I realize the input layer, which you wrote, needs both, even though the index seems useless in test phase. 

So I append the index. Consequently, it works out.

**Comment by tatarchm** [comment]
I see, thank you for this information.

**Comment by hzxie** [comment]
The same problem here. But I don't think there's anything wrong with my dataset.
Here's the example of my `dataset.txt`:

```
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/00.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/01.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/02.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/03.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/04.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/05.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/06.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/07.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/08.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/09.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/10.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/11.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/12.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/13.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/14.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/15.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/16.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/17.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/18.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/19.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/20.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/21.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/22.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/358ddbe8b39125e9e81913b1de19c3f7/rendering/23.png 1240
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/cdec84be0cc9364eecfe83f5db813c4f/rendering/00.png 2149
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/cdec84be0cc9364eecfe83f5db813c4f/rendering/01.png 2149
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/cdec84be0cc9364eecfe83f5db813c4f/rendering/02.png 2149
/home/hzxie/Desktop/Temporary/Datasets/ShapeNet/ShapeNetRendering/02958343/cdec84be0cc9364eecfe83f5db813c4f/rendering/03.png 2149
```

Can you tell me what the problem is?
Thank you very much.

**Comment by tatarchm** [comment]
Hi,

Were you able to solve the problem? I can't see your comment on GitHub. If
not, could you please send me the files you are trying to load and all the
specifications?

Best,
Maxim

**Comment by hzxie** [comment]
@mtatarchenko 
I've solved this problem.
So I deleted the comment.

**Comment by ThibaultGROUEIX** [comment]
@mtatarchenko Why delete it ?
I've ran into the same issue after compiling the repo and executing runtest successfully, I added the data, and tried to run the scripts for single_view_3d,  ``` ./train_pred.sh```. And it gives me the same input stream error. Can you explain how you solved it to someone not used to caffe ?

**Comment by sherrychen32** [comment]
@hzxie 
Can you tell me how you solve the problem?
I also met the same problem. The test file I used is "shapenet_cars_rendered_new_test.txt". But it is the original file. And I just run ./test.sh.

**Comment by hzxie** [comment]
@sherrychen32 
Please check your input and output files carefully.

**Comment by sherrychen32** [comment]
The following is the "test_net.prototxt" file. And the input files I found are "shapenet_cars_rendered_new_test.txt" and "model_names.txt". 


  #------------------------------------------------------------------------------------------------------------
  #-- INPUT DATA
  #------------------------------------------------------------------------------------------------------------
  layer{name: "input_images" type: "ImageData"
      top: "input_images" top: "input_labels"
      transform_param {scale: 0.00392156862}
      image_data_param{source: "shapenet_cars_rendered_new_test.txt" batch_size: 16 shuffle: false}}
 
  layer {name: "octree_models" type: "OGNData"
    bottom: "input_labels" top: "octree_model_values" top: "octree_labels"
    ogn_data_param {batch_size: 16 source: "model_names.txt" preload_data: false}}
 
  layer{name: "silence_octree_values" type: "Silence"
    bottom: "octree_model_values"}
 
  layer{name: "silence_octree_labels" type: "Silence"
    bottom: "octree_labels"}
  #------------------------------------------------------------------------------------------------------------

 
For the input images, I had put them into the corresponding directory, and can be found by caffe.
I'm not quite sure where can I get .ot file. Is that the reason caused the problem?

The error message is as following:

#----------------------------------------------------------------------------------------
I0201 23:38:53.347965 51452 caffe.cpp:290] Running for 5 iterations.
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
*** Aborted at 1517499533 (unix time) try "date -d @1517499533" if you are using GNU date ***
PC: @     0x7f40e1e62107 gsignal
*** SIGABRT (@0x199a0000c8fc) received by PID 51452 (TID 0x7f40f1c68a40) from PID 51452; stack trace: ***
    @     0x7f40f05e78d0 (unknown)
    @     0x7f40e1e62107 gsignal
    @     0x7f40e1e634e8 abort
    @     0x7f40e247b66d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f40e24796c6 (unknown)
    @     0x7f40e2479711 std::terminate()
    @     0x7f40e2479929 __cxa_throw
    @     0x7f40f14e3f24 boost::serialization::throw_exception<>()
    @     0x7f40f0ab6f6c boost::archive::text_iarchive_impl<>::load()
    @     0x7f40f0ab72f5 boost::archive::basic_text_iarchive<>::init()
    @     0x7f40f0ab7498 boost::archive::text_iarchive_impl<>::text_iarchive_impl()
    @     0x7f40f14e04ca GeneralOctree<>::from_file()
    @     0x7f40f14e0d10 caffe::OGNDataLayer<>::select_next_batch_models()
    @     0x7f40f14e11cc caffe::OGNDataLayer<>::Reshape()
    @     0x7f40f1474caa caffe::Net<>::ForwardFromTo()
    @     0x7f40f1475057 caffe::Net<>::Forward()
    @           0x40a4f3 test()
    @           0x408610 main
    @     0x7f40e1e4eb45 __libc_start_main
    @           0x408e08 (unknown)
    @                0x0 (unknown)
./test.sh: line 1: 51452 Aborted                 
caffe test --model test_net.prototxt --weights=snapshots/snapshot_iter_136000.caffemodel --gpu 0 --iterations 5
#----------------------------------------------------------------------------------------

**Comment by hzxie** [comment]
@sherrychen32 
You can generate `.ot` files with `ogn_converter`.

**Comment by sherrychen32** [comment]
@hzxie Thank you so much, after I put the .ot file into data/ directory it works.

**Comment by sylqiu** [comment]
@sherrychen32  I had the same problem.Thank you so much for the solution! How did you find it?
