### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by kealennieh** [mtatarchenko/ogn#5]
Hi, Maxim,

Sorry to bother you again.  I've seen your paper recently. Now I'm wondering how to get the evaluation between the output and ground truth. They may be in different coordinates. Have you transferred them into one common coordinate? Can you share your evaluation scripts? Thanks in advance!

Best wishes,
Kealen

**Comment by sdukaka** [comment]
Hi, have you encountered with boost::archive::archive_exception in the training stage, I have fixed the bug in testing.  However, when I train OGN by using my  own data, I have the same problem in tesing, do you have some advice ?

**Comment by kealennieh** [comment]
I've never met that question in training phase. Since you get the valid image path in training.txt and the right ot model path in model_names.txt, it will work out. The networks used in testing and training have just a liite different.

**Comment by sdukaka** [comment]
OK，How long have you train this network?

**Comment by kealennieh** [comment]
Well, it depends on many factors, such as your batch, your GPU, your iteration and so on. It's hard to tell how long you will spend.
