### ISSUE TITLE
about mini-level > 4 

### ISSUE THREAD

**Issue by brotherNanNan** [mtatarchenko/ogn#6]
Hi,
      I have a question. Do i need change the structure of network if i generate .ot file whose mini-level > 4 ? thanks.

**Comment by tatarchm** [comment]
Yes, you do. The level number L corresponds to the spatial resolution of the feature map R as R = pow(2, L). If you change L, you will need to accordingly change the number of dense convolutional layers and the number of octree layers in the decoder.
