### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by umbra99** [mtatarchenko/ogn#7]
Wow, that looks realy good. 
I have been looking into voxels and neural networks recently, but the fact that I can't reasonably run more then 32^3 models on my PC is realy annoying. So your paper was very exciting to me. Sadly I have only experience in Tensorflow and Theano. So I just wanted to ask if you guys have any planes of making a Tensorflow layer for this.
Thank you very much for your time.

**Comment by tatarchm** [comment]
Thank you for your interest in our work! We do consider implementing the framework in Tensorflow, but it's not likely to happen within the next few months.
