### ISSUE TITLE
boost referencing problem

### ISSUE THREAD

**Issue by alitou** [mtatarchenko/ogn#8]
When I try to compile the ogn caffe I got into some boost referencing problem. For example .build_release/lib/libcaffe.so: undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load_override(boost::archive::class_name_type&, int)'.
How can I solve it?

**Comment by tatarchm** [comment]
It looks like the linker cannot find one of the boost library binaries. Are you sure you've installed a full version of boost (not header-only)? Can you check the linker paths?

**Comment by asnt** [comment]
Same problem here. I manually added boost serialization and program_options to the linker flags:
```
diff --git a/Makefile b/Makefile
index 77900b6..15c51df 100644
--- a/Makefile
+++ b/Makefile
@@ -178,7 +178,8 @@ ifneq ($(CPU_ONLY), 1)
 	LIBRARIES := cudart cublas curand
 endif
 
-LIBRARIES += glog gflags protobuf boost_system boost_filesystem m hdf5_hl hdf5
+LIBRARIES += glog gflags protobuf boost_system boost_filesystem \
+			 boost_serialization boost_program_options m hdf5_hl hdf5
 
 # handle IO dependencies
 USE_LEVELDB ?= 1
```

**Comment by tatarchm** [comment]
Are you trying to compile using the Makefile? We did not add support for Makefile builds, if you want to use it, you have to configure everything yourself. The suggested build system is CMake. To compile, install the dependencies, then run

```bash
mkdir build
cd build
cmake ..
make all
```
