### ISSUE TITLE
ogn_converter.cpp

### ISSUE THREAD

**Issue by gk2500** [mtatarchenko/ogn#9]
Doesn't seem to work in direction of binvox -> octree file (.ot). Is this the actual tool you used to get octree (.ot) files?
I see in the Python utilities a way to covert .ot to .binvox, but not the other way around. Did you include utilities in C or Python to convert a binvox file to a .ot format that is usable with your network?
Thanks...

**Comment by tatarchm** [comment]
What does not work exactly? You can convert .binvox files to .ot files by running

`ogn_converter -i file.binvox -o file.ot -l n`

where n is the integer minimum octree level.

**Comment by gregkocher** [comment]
Thanks. Do you have Python utilities included to accomplish this same task of .binvox -> .ot? Because there were some issues when trying to compile the ogn_converter.cpp.
Thanks.

**Comment by tatarchm** [comment]
Can you please be more specific - what issues? It should compile automatically with the rest of the framework. There is currently no python function for writing .ot files, only one for reading is implemented.

**Comment by gregkocher** [comment]
Hi, thanks for the fast response. When I compile, I get some errors such as:

...   /tools/ogn_converter.cpp:82:48: error: conversion from ‘GeneralVoxelGrid<unsigned char>’ to non-scalar type ‘VoxelGrid {aka OccupancyVoxelGrid}’ requested
             VoxelGrid vg = octree.to_voxel_grid();

....  /tools/ogn_converter.cpp:83:16: error: ‘VoxelGrid {aka class OccupancyVoxelGrid}’ has no member named ‘write_binvox’
             vg.write_binvox(output_string);


...  /tools/ogn_converter.cpp:83:29: error: ‘output_string’ was not declared in this scope
             vg.write_binvox(output_string)


Then when looking through the C code it seemed as if there might be a relevant portion that was not implemented which might be causing this.

**Comment by tatarchm** [comment]
How exaclty are you compiling? The project is supposed to be compiled using CMake, which (after installing the dependencies) amounts to:

```bash
mkdir build
cd build
cmake ..
make all
```

**Comment by gregkocher** [comment]
Excellent, the ogn_converter seems to be working great. And for voxel grids on the order of what you had in your paper [64, 128, 256,...] would you recommend keeping min level = 4? Or would there be much benefit to keeping levels 1,2,3 which would have coarser large scale information?

**Comment by tatarchm** [comment]
If you set min level to be small, the memory consumption decreases, but the number of times you need to propagate features using predicted information increases. Setting it to 4 gave the best empirical results in my experiments, but it may be very different for different tasks/datasets.
